### ISSUE TITLE
Design ERC CI job

### ISSUE THREAD

**Issue by jaylamb** [apcountryman/prototype-kicad-project-ci-cd#1]
Add Electrical Rules Check (ERC) CI job. This job can then be run as a part of a commit or release to ensure a schematic's compliance with a project's as-configured electrical rules. The script should succeed silently, and present the results of any portion of the check that fails.

- [ ] Add `ci/electrical-rules-check` script that supports the following options:
    * `--version`: display the version of the script
    * `--help`: display the help text for the script
- [ ] Add Electrical Rules Check CI job to the script
    * The [KiAuto](https://pypi.org/project/kiauto/) project should be imported as a submodule to this project.
        * This script should leverage the automated ERC provided by the KiAuto project:
        `"$repository_dir/utilities/KiAuto/src/eeschema_do" run_erc -w "${schematics[@]}" "${build_dir}"`

**Comment by apcountryman** [comment]
Changing `ci/electrical-rules-check` to `ci/check-electrical-rules-compliance` follows the script naming convention (verb first) and is slightly more descriptive.

If no schematic files are found, the script should succeed. To do this, `eeschema_do` should not be invoked if no schematic files are found.

It appears that `eeschema_do`'s ERC check can only be run against a single top level schematic file at a time which will require looping over the list of found top level schematic files. Also, a schematic sheet file naming convention (`<top level schematic name>-sheet-<sheet functional description>.sch`) will need to be adopted.

Existing scripts currently capture the path to the repository in a variable named `repository`, not `repository_dir`.

Other than these, this design looks LGTM. I'll open a `type-feature` issue for implementing this new feature shortly.
