### ISSUE TITLE
Add electrical rules compliance CI job

### ISSUE THREAD

**Issue by apcountryman** [apcountryman/prototype-kicad-project-ci-cd#2]
Add electrical rules compliance CI job. The proposed design is outlined in #1.
- [x] Add https://github.com/INTI-CMNB/KiAuto as a project submodule
```bash
git submodule add ../KiAuto utilities/KiAuto
```
- [x] Add electrical rules compliance check CI script (`ci/check-electrical-rules-compliance`)
    - [x] Supported options:
        - [x] `--help`: See other project scripts
        - [x] `--version`: See other project scripts
    - [x] `function error()`: See other project scripts
    - [x] `function abort()`: See other project scripts
    - [x] `function display_help_text()`: See other project scripts
    - [x] `function display_version()`: See other project scripts
    - [x] `function main()`: See other project scripts
    - [x] `function check_electrical_rules_compliance()`:
```bash
local schematics; mapfile -t schematics < <( git -C "$repository" ls-files '*.sch' ':!:*-sheet-*.sch' | xargs -r -d '\n' -I '{}' find "$repository/{}" ); readonly schematics

for schematic in "${schematics[@]}"; do
    if ! "$repository/utilities/KiAuto/src/eeschema_do" run_erc -w "$schematic" "$repository"; then
        cat "$repository/"*.erc
        abort
    fi
done
```
- [x] Add electrical rules compliance check CI job (`check-electrical-rules-compliance`) to `.github/workflows/ci.yml`
    - [x] `name: Check electrical rules compliance`
    - [x] Steps:
        - [x] Checkout (needs submodules)
        - [x] `name: Check electrical rules compliance`, `run: ./ci/check-electrical-rules-compliance`

**Comment by jaylamb** [comment]
I'm unable to assign the issue to myself, or to place it into an "in development" status. Please assign this issue to me when you get a chance. Thanks! - JDL
