### ISSUE TITLE
Fix CI scripts for KiCad 6 compatibility

### ISSUE THREAD

**Issue by jaylamb** [apcountryman/prototype-kicad-project-ci-cd#49]
During development of #44, a few small issues have been uncovered with the CI scripts:
- [x] https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/0a7bf453a597e092193eecf6f4821b3eb687dfdd/ci/check-design-rules-compliance#L70 `.drt` should be `.rpt`
- [x] https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/0a7bf453a597e092193eecf6f4821b3eb687dfdd/ci/check-electrical-rules-compliance#L63 `.sch` should be `.kicad_sch`
- [x] https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/0a7bf453a597e092193eecf6f4821b3eb687dfdd/ci/generate-interactive-bom#L62 `.pro` should be `.kicad_pro`
- [x] https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/0a7bf453a597e092193eecf6f4821b3eb687dfdd/ci/generate-interactive-bom#L70 `.pro` should be `.kicad_pro`
- [x] https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/0a7bf453a597e092193eecf6f4821b3eb687dfdd/ci/generate-interactive-bom#L73 `if ! git ...` should be `if git ...`
- [x] https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/0a7bf453a597e092193eecf6f4821b3eb687dfdd/ci/generate-pcb-renders#L61 `.pro` should be `.kicad_pro`
- [x] https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/0a7bf453a597e092193eecf6f4821b3eb687dfdd/ci/generate-pcb-renders#L69 `.pro` should be `.kicad_pro`
- [x] https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/0a7bf453a597e092193eecf6f4821b3eb687dfdd/ci/generate-pcb-renders#L72 `if ! git ...` should be `if git ...`
- [x] https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/0a7bf453a597e092193eecf6f4821b3eb687dfdd/ci/generate-production-files#L62 `.pro` should be `.kicad_pro`
- [x] https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/0a7bf453a597e092193eecf6f4821b3eb687dfdd/ci/generate-production-files#L70 `.pro` should be `.kicad_pro`
- [x] https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/0a7bf453a597e092193eecf6f4821b3eb687dfdd/ci/generate-production-files#L73 `if ! git ...` should be `if git ...`
- [x] https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/0a7bf453a597e092193eecf6f4821b3eb687dfdd/ci/generate-schematic-pdf#L62 `.pro` should be `.kicad_pro`
- [x] https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/0a7bf453a597e092193eecf6f4821b3eb687dfdd/ci/generate-schematic-pdf#L70 `.pro` should be `.kicad_pro`
- [x] https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/0a7bf453a597e092193eecf6f4821b3eb687dfdd/ci/generate-schematic-pdf#L71 `.sch` should be `.kicad_sch`
- [x] https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/0a7bf453a597e092193eecf6f4821b3eb687dfdd/ci/generate-schematic-pdf#L73 `if ! git ...` should be `if git ...`
- [x] https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/0a7bf453a597e092193eecf6f4821b3eb687dfdd/ci/generate-traditional-bom#L62 `.pro` should be `.kicad_pro`
- [x] https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/0a7bf453a597e092193eecf6f4821b3eb687dfdd/ci/generate-traditional-bom#L70 `.pro` should be `.kicad_pro`
- [x] https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/0a7bf453a597e092193eecf6f4821b3eb687dfdd/ci/generate-traditional-bom#L71 `.sch` should be `.kicad_sch`
- [x] https://github.com/apcountryman/prototype-kicad-project-ci-cd/blob/0a7bf453a597e092193eecf6f4821b3eb687dfdd/ci/generate-traditional-bom#L73 `if ! git ...` should be `if git ...`

**Comment by apcountryman** [comment]
I'll fix these shortly. Looks like `ci/check-electrical-rules-compliance` also needs a `.sch` -> `.kicad_sch` extension change so it will be added to the list of things to fix.

**Comment by jaylamb** [comment]
> I'll fix these shortly. Looks like `ci/check-electrical-rules-compliance` also needs a `.sch` -> `.kicad_sch` extension change so it will be added to the list of things to fix.

Sounds good. I'll merge things in and be back at it a little later on.
